apiVersion: v1
kind: Service
metadata:
  name: simple-api
  namespace: api
spec:
  selector:
    app: simpel-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer